# UI defaults configuration file. It is automatically loaded if located at configs/webui/webui_streamlit.yaml.
# Any changes made here will be available automatically on the web app without having to stop it.
# You may add overrides in a file named "userconfig_streamlit.yaml" in this folder, which can contain any subset
# of the properties below.
general:
  gpu: 0
  outdir: "/gdrive/MyDrive/sd_anims_new"
  ckpt: "/gdrive/MyDrive/sd-v1-4.ckpt"
  default_model: "Stable Diffusion v1.4"
  default_model_config: "configs/stable-diffusion/v1-inference.yaml"
  default_model_path: "/gdrive/MyDrive/sd-v1-4.ckpt"
  default_path_mode: "root"
  default_path_mode_index: 1
  GFPGAN_dir: /content/models
